#!/bin/bash
##first install
echo "======================";
echo "Build android app"
echo "======================";

yarn install
yarn build
cp -r build cordova 

echo "======================";
echo "web app builded"
echo "======================";

cd cordova/
cordova platform add electron

echo "======================";
echo "add android for cordova"
echo "======================";

rm -rf www/
mv build/ www/

cordova build electron
